# Generated by Django 5.2.13 on 2026-04-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Штрих-код')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
            ],
            options={
                'db_table': 'sku',
            },
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=20, unique=True, verbose_name='Код ячейки')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занята')),
            ],
            options={
                'db_table': 'storage_bin',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('picking', 'Сборка'), ('packed', 'Упакован'), ('shipped', 'Отгружен'), ('cancelled', 'Отказ/Отмена')], default='new', max_length=20)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.sku')),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.storagebin')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
